# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-19 03:48
from __future__ import unicode_literals

from django.db import migrations, models
import weddings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wedding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('zodiacsign', models.CharField(choices=[('Aries', '\u2648'), ('Taurus', '\u2649'), ('Gemini', '\u264a'), ('Cancer', '\u264b'), ('Leo', '\u264c'), ('Virgo', '\u264d'), ('Libro', '\u264e'), ('Scorpius', '\u264f'), ('Sagittarius', '\u2650'), ('Capicorn', '\u2651'), ('Aquarius', '\u2652'), ('Pisces', '\u2653')], default='Virgo', max_length=11)),
                ('yourface', models.ImageField(upload_to=weddings.models.upload_location)),
                ('whoyouare', models.TextField(max_length=700)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
