# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-20 15:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0003_auto_20170120_1010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wedding',
            options={'managed': False},
        ),
    ]
