# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-20 15:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0004_auto_20170120_1021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wedding',
            options={},
        ),
    ]
