# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-20 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0007_auto_20170120_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='wedding',
            name='fake',
            field=models.CharField(default='s', max_length=2),
            preserve_default=False,
        ),
    ]
