# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-20 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0008_wedding_fake'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wedding',
            name='fake',
        ),
        migrations.RemoveField(
            model_name='wedding',
            name='yourface',
        ),
        migrations.AlterField(
            model_name='wedding',
            name='height_field',
            field=models.IntegerField(blank=True, default=800, null=True),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='width_field',
            field=models.IntegerField(blank=True, default=800, null=True),
        ),
    ]
