# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-20 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20160921_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='share',
            field=models.CharField(default='<meta property="og:image" content="/static/img/emblemmatic-spencer-tech-consulting-&-solutions-logo-60.png"', max_length=4000),
        ),
    ]
