# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-20 21:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_share'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='share',
        ),
    ]
