# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-21 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_post_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(height_field='height_field', upload_to=posts.models.upload_location, width_field='width_field'),
        ),
    ]
