# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-15 04:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20161129_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='draft',
        ),
    ]
