# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-17 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20170316_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('ipadd', models.GenericIPAddressField()),
            ],
        ),
    ]
