# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-20 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_subscriptionlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionlist',
            name='ipadd',
        ),
    ]
