# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-20 21:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_remove_subscriptionlist_ipadd'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscriptionList',
        ),
    ]
