# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-21 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_delete_subscriptionlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fakeattr',
            field=models.NullBooleanField(),
        ),
    ]
