# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-21 18:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_post_fakeattr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='fakeattr',
        ),
    ]
